services:
  mongo:
    image: mongo:5.0.28-focal
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: rtc-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/rtc
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - mongo
    restart: "always"

  frontend:
    build: ./frontend
    container_name: rtc-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

volumes:
  mongo-data:
